function RECORD = build_gui_recording(fig)
	GUI.fig = fig;
	clear fig

	%% Static text
	static = zeros(1,3);
	for m = 1:3
		static(m) = uicontrol(				'Units','pixels');
	end; clear m
	set(static,								'Style','text',...
											'HorizontalAlignment','left',...
											'BackgroundColor',[.3 .3 .3],...
											'ForegroundColor',[0 .7 .7])
	set(static(1),							'Position',[761 419 80 15],...
											'String','Total Waypoints');
	set(static(2),							'Position',[761 453 80 15],...
											'String','Active Waypoint');
	set(static(3),							'Position',[846+156 680 130 15],...
											'String','Waypoint Sequence Editor',...
											'ForegroundColor',[1 1 1]);

	%% Draw waypoint indicators
	RECORD.activeWaypoint = uicontrol(		'Units','pixels',...
											'Position',[726 446 30 30],...
											'String','01');
	RECORD.totalWaypoint = uicontrol(		'Units','pixels',...
											'Position',[726 412 30 30],...
											'String','01');
	set([RECORD.activeWaypoint RECORD.totalWaypoint],...
											'Style','text',...
											'HorizontalAlignment','center',...
											'BackgroundColor',[.4 .4 .4],...
											'ForegroundColor',[0 1 1],...
											'FontSize',18,...
											'FontWeight','demi')

	%% Draw total waypoint buttons
	IMAGES.plus = imread('IMAGES -- Plus.jpg');
	IMAGES.minus = imread('IMAGES -- Minus.jpg');
	RECORD.addWaypoint = uicontrol(			'Units','pixels',...
											'Position',[696 426 25 20],...
											'CData',IMAGES.plus,...
											'TooltipString','Add a waypoint to the bottom of the list');
	RECORD.reduceWaypoint = uicontrol(		'Units','pixels',...
											'Position',[696 406 25 20],...
											'CData',IMAGES.minus,...
											'TooltipString','Delete last waypoint in the list');
	set([RECORD.addWaypoint RECORD.reduceWaypoint],...
											'FontSize',18,...
											'FontWeight','demi')

	%% Draw waypoint listbox
	RECORD.listbox = uicontrol(			'Units','pixels',...
										'Tag','Waypoint Listbox',...
										'Max',2,...
										'Min',1,...
										'Parent',GUI.fig,...
										'Position',[696 482 437 193],...
										'Style','listbox',...
										'FontName','FixedWidth',...
										'FontSize',9);

	%% Draw New, Load, Save
	IMAGES.new = imread('IMAGES -- New.jpg');
	IMAGES.load = imread('IMAGES -- Load.jpg');
	IMAGES.save = imread('IMAGES -- Save.jpg');
	RECORD.newSequence = uicontrol(		'Units','pixels',...
										'Parent',GUI.fig,...
										'Position',[696 680 50 20],...
										'CData',IMAGES.new);
	RECORD.loadSequence = uicontrol(	'Units','pixels',...
										'Parent',GUI.fig,...
										'Position',[746+5 680 50 20],...
										'CData',IMAGES.load);
	RECORD.saveSequence = uicontrol(	'Units','pixels',...
										'Parent',GUI.fig,...
										'Position',[796+10 680 50 20],...
										'CData',IMAGES.save);

	%% Draw set waypoint button
	IMAGES.animate = imread('IMAGES -- Animate.jpg');
	IMAGES.set = imread('IMAGES -- Set.jpg');	
	RECORD.playbackWaypoint = uicontrol('Units','pixels',...
										'Parent',GUI.fig,...
										'Position',[851 412 77 30],...
										'Interruptible','off',...
										'CData',IMAGES.animate,...
										'BusyAction','cancel',...
										'TooltipString',' Animate entire sequence ');
	RECORD.setWaypoint = uicontrol(		'Units','pixels',...
										'Parent',GUI.fig,...
										'Position',[851 446 77 30],...
										'CData',IMAGES.set,...
										'TooltipString',' Set position at active waypoint. If this is the last waypoint, a new waypoint will be added. ');
end