function GUI = build_gui_positioning
    fh(1) = figure(		...%Boolean
						'BackingStore','off',...
						'DockControls','off',...
						'HitTest','off',...
						'Interruptible','off',...
						'NumberTitle','off',...
						'Resize','off',...
						'SelectionHighlight','off',...
						...%String Choices
						'BusyAction','cancel',...
						'MenuBar','none',...
						'Renderer','OpenGL',...
						'Toolbar','none',...
						...%String
						'Name','TeachMover Virtual Command',...
						'Tag','Main Figure',...
						...%Numerical
						'Color',[.3 .3 .3],...
						'Position',[6+50 82-50 1140 720]);
	set(fh,'Units','normalized')
	set(fh,'Visible','on')

	panelh = zeros(1,2);
	for m = 1:2
		panelh(m) = uipanel('Units','pixels');
	end; clear m	
	set(panelh(1),		'Position',[696 9 226 384],...
						'Tag','Panel FK Sliders',...
						'Title','Forward Kinematics');
	set(panelh(2),		'Units','pixels',...
						'Position',[925 9 211 384],...
						'Tag','Panel IK Sliders',...
						'Title','Inverse Kinematics');
	set(panelh,			'BackgroundColor',[.3 .3 .3],...
						'BorderType','etchedout',...
						'BorderWidth',1,...
						'BusyAction','cancel',...
						'Clipping','on',...
						'FontName','Arial',...
						'FontSize',8,...
						'ForegroundColor',[1 1 1],...
						'HighlightColor',[.1 .1 .1],...
						'HitTest','off',...
						'Interruptible','off',...
						'SelectionHighlight','off',...
						'TitlePosition','lefttop',...
						'Units','normalized');

	ah = zeros(1,6);
	for m = 1:6
		ah(m) = axes('Units','pixels');
	end; clear m
	set(ah(1),			'Tag','Axes Top View',...
						'Position',[20 19 271 376]);
	set(ah(2),			'Tag','Axes Front View',...
						'Position',[307 411 376 289]);
	set(ah(3),			'Tag','Axes Lateral View',...
						'Position',[20 411 271 289]);
	set(ah(4),			'Tag','Axes 3D View',...
						'Position',[307 169 376 236]);
	set(ah(5),			'Tag','Axes Pitch',...
						'Position',[312 19 124 124]);
	set(ah(6),			'Tag','Axes Roll',...
						'Position',[453 19 124 124]);
	set(ah(1:4),		'XLim',[-2 4.55],...
						'YLim',[-4.55 4.55],...
						'ZLim',[0 7])
	set(ah,				'Parent',fh,...		% Common settings for all axes
						'Box','on',...
						'HitTest','on',...
						'DataAspectRatio',[1 1 1],...
						'Color',[.2 .2 .2],...
						'XGrid','on',...
						'YGrid','on',...
						'ZGrid','on',...
						'XColor',[0 .7 .7],...
						'YColor',[0 .7 .7],...
						'ZColor',[0 .7 .7],...
						'FontName','Arial',...
						'FontSize',8)
	set(ah(1),			'XTickLabel',[],...	% Finalize axes settings
						'YAxisLocation','right')
	set(ah(2),			'View',[90 0],...
						'ZTick',0:7,...
						'ZTickLabel',0:7)
	set(ah(3),			'View',[0 0],...
						'ZTick',0:7,...
						'ZTickLabel',[])
	set(ah(4),			'CameraViewAngle',7,...
						'Color','none',...
						'Projection','perspective',...
						'View',[75 30],...
						'Visible','off',...
						'XLim',[-1 4.55],...
						'XGrid','off',...
						'YGrid','off',...
						'ZGrid','off')
	set(ah(5),			'XTick',-1:0.5:1,...
						'YTick',-1:0.5:1,...
						'XLim',[-1 1],...
						'YLim',[-1 1],...
						'XTickLabel',[],...
						'YTickLabel',[])
	set(ah(6),			'XTick',-1.5:0.75:1.5,...
						'YTick',-1.5:0.75:1.5,...
						'XLim',[-2.5 2.5],...
						'YLim',[-2.5 2.5],...
						'XTickLabel',[],...
						'YTickLabel',[])
	a = 4;
	for m = 1:4								% Draw home coordinate system
		lh(1) = line([0 a],[0 0],[0 0],...
						'Color',[1 0 0]);
		lh(2) = line([0 0],[0 a],[0 0],...
						'Color',[0 1 0]);
		lh(3) = line([0 0],[0 0],[0 a],...
						'Color',[0 0 1]);
		set(lh,			'Parent',ah(m),...
						'LineWidth',2)
	end; clear a m lh
	x = 1.5*cos(0:0.01:2*pi);
	y = 1.5*sin(0:0.01:2*pi);
	line(x,y,	'Parent',ah(6),...
				'Color',[.5 .5 .5],...
				'HitTest','off')
	x = 0.75*cos(0:0.01:2*pi);
	y = 0.75*sin(0:0.01:2*pi);
	line(x,y,	'Parent',ah(6),...
				'Color',[.5 .5 .5],...
				'HitTest','off')
	clear x y

	sliderh = zeros(1,9);
	for m = 1:9
		sliderh(m) = axes('Units','pixels');
	end; clear m
	set(sliderh(1),		'Tag','Slider Trunk',...	% Slider Trunk					
						'Position',[24 40 24 325],...
						'YLim',[-90 90]);
	set(sliderh(2),		'Tag','Slider Shoulder',...	% Slider Shoulder
						'Position',[77 40 24 325],...
						'YLim',[-35 144]);
	set(sliderh(3),		'Tag','Slider Elbow',...	% Slider Elbow
						'Position',[132 40 24 325],...
						'YLim',[-149 0]);
	set(sliderh(4),		'Tag','Slider Pitch',...	% Slider Pitch
						'Position',[31 40 24 325],...
						'YLim',[-180 180]);
	set(sliderh(5),		'Tag','Slider Roll',...		% Slider Roll
						'Position',[187 40 24 325],...
						'YLim',[-270 270]);
	set(sliderh(6),		'Tag','Slider X',...		% Slider X
						'Position',[79 40 24 325],...
						'YLim',[0 4.6],...
						'YTick',0:4);
	set(sliderh(7),		'Tag','Slider Y',...		% Slider Y
						'Position',[128 40 24 325],...
						'YLim',[-4.55 4.55],...
						'YTick',-4:4);
	set(sliderh(8),		'Tag','Slider Z',...		% Slider Z
						'Position',[177 40 24 325],...
						'YLim',[0 7]);
	set(sliderh(9),		'Tag','Slider Grip',...		% Slider Grip
						'Position',[582 19 24 124],...
						'YLim',[0 3]);
	set(sliderh([1:3 5]),	'Parent',panelh(1))
	set(sliderh([4 6:8]),	'Parent',panelh(2))
	set(sliderh,		...%Boolean
						'Box','on',...
						'Interruptible','off',...
						'BusyAction','cancel',...
						...%String Choices
						'FontSize',8,...
						'GridLineStyle',':',...
						...%String
						'FontName','Arial',...
						...%Numerical
						'Color',[.2 .2 .2],...
						'DataAspectRatioMode','auto',...
						'PlotBoxAspectRatioMode','auto',...
						...%Callbacks
						...%XYZ Settings
						'XColor',[0 .7 .7],...
						'YColor',[0 .7 .7],...
						'XLim',[-5 2.5],...
						'XTick',[],...
						'YGrid','on',...
						'Units','normalized');
	set(sliderh(9),		'Box','on',...
						'DataAspectRatioMode','auto',...
						'PlotBoxAspectRatioMode','auto',...
						'XColor',[0 .7 .7],...
						'YAxisLocation','right')

	edittexth = zeros(1,9);
	for m = 1:9
		edittexth(m) = uicontrol('Units','pixels');
	end; clear m
	set(edittexth(1),			'Position',[15 18 43 20],...
								'Tag','Edittext Trunk',...
								'TooltipString','Trunk Angle');
	set(edittexth(2),			'Position',[68 18 43 20],...
								'Tag','Edittext Shoulder',...
								'TooltipString','Shoulder Angle');
	set(edittexth(3),			'Position',[123 18 43 20],...
								'Tag','Edittext Elbow',...
								'TooltipString','Elbow Angle');
	set(edittexth(4),			'Position',[22 18 45 20],...
								'Tag','Edittext Pitch',...
								'TooltipString','Pitch Angle (with respect to ground)');
	set(edittexth(5),			'Position',[178 18 43 20],...
								'Tag','Edittext Roll',...
								'TooltipString','Roll Angle');
	set(edittexth(6),			'Position',[74 18 35 20],...
								'Tag','Edittext X',...
								'TooltipString','X Coordinate');
	set(edittexth(7),			'Position',[123 18 35 20],...
								'Tag','Edittext Y',...
								'TooltipString','Y Coordinate');
	set(edittexth(8),			'Position',[172 18 35 20],...
								'Tag','Edittext Z',...
								'TooltipString','Z Coordinate');
	set(edittexth(9),			'Position',[626 36 35 20],...
								'Tag','Edittext Grip',...
								'TooltipString','Grip Opening');
	set(edittexth([1:3 5]),		'Parent',panelh(1))
	set(edittexth([4 6:8]),		'Parent',panelh(2))
	set(edittexth(9),			'Parent',fh)
	set(edittexth,				'BackgroundColor',[1 1 1],...
								'BusyAction','cancel',...
								'FontName','Arial',...
								'FontSize',8,...
								'ForegroundColor',[0 0 0],...
								'HitTest','off',...
								'Interruptible','off',...
								'Max',1,...
								'Min',1,...
								'SelectionHighlight','off',...
								'String','0.0',...
								'Style','edit',...
								'Units','normalized')

	statictexth = zeros(1,15);
	for m = 1:15
		statictexth(m) = uicontrol('Units','pixels');
	end; clear m
	set(statictexth(1),			'Position',[24 5 25 10],...
								'String','TR');
	set(statictexth(2),			'Position',[77 5 25 10],...
								'String','SH');
	set(statictexth(3),			'Position',[132 5 25 10],...
								'String','EL');
	set(statictexth(4),			'Position',[33 5 25 10],...
								'String','P');
	set(statictexth(5),			'Position',[187 5 25 10],...
								'String','R');
	set(statictexth(6),			'Position',[79 5 25 10],...
								'String','x');
	set(statictexth(7),			'Position',[128 5 25 10],...
								'String','y');
	set(statictexth(8),			'Position',[177 5 25 10],...
								'String','z');
	set(statictexth(9),			'Position',[630 19 25 10],...
								'String','GR');
	set(statictexth(10),		'Position',[21 20 50 12],...
								'String','Top View');
	set(statictexth(11),		'Position',[622 687 60 12],...
								'String','Front View');
	set(statictexth(12),		'Position',[21 687 65 12],...
								'String','Lateral View');
	set(statictexth(13),		'Position',[312 150 45 12],...
								'String','3D View');
	set(statictexth(14),		'Position',[313 20 25 12],...
								'String','Pitch');
	set(statictexth(15),		'Position',[454 20 65 12],...
								'String','Roll and Grip');
	set(statictexth([1:3 5]),	'Parent',panelh(1))
	set(statictexth([4 6:8]),	'Parent',panelh(2))
	set(statictexth(9:15),		'Parent',fh)
	set(statictexth([1:9 13]),	'BackgroundColor',[.3 .3 .3])
	set(statictexth([10:12 14:15]),'BackgroundColor',[.3 .3 .3])
	set(statictexth,			'FontName','Arial',...
								'FontSize',8,...
								'ForegroundColor',[1 1 1],...
								'HitTest','off',...
								'SelectionHighlight','off',...
								'Style','text',...
								'Units','normalized');
	clear statictexth

	slidemarkh = zeros(1,9);
	for m = 1:9
		switch m
			case 9
				slidemarkh(m) = line(	-2,0,...
										'Parent',sliderh(9));
			otherwise
				slidemarkh(m) = line(	-0.5,0,...
										'Parent',sliderh(m));
		end
	end;	clear m
	set(slidemarkh,		'Marker','<',...
						'MarkerSize',17,...
						'MarkerEdgeColor',[0 1 0],...
						'MarkerFaceColor',[0 .5 0],...
						'HitTest','off')
	set(slidemarkh(9),	'Marker','>')
	IMAGES.warning = imread('IMAGES -- Warning.jpg');
	safetytexth = uicontrol('Units','pixels',...
							'Position',[337-20 240 326+35 51],...
							'Style','pushbutton',...
							'CData',IMAGES.warning,...
							'Visible','off');
	IMAGES.home = imread('IMAGES -- Home.jpg');
	homebuttonh = uicontrol('Units','pixels',...
							'Position',[312 340 40 40],...
							'Style','pushbutton',...
							'CData',IMAGES.home);

	%%	Store all graphics handles into GUI structure
	GUI.fig = fh;
	GUI.viewports = ah;
	GUI.sliders = sliderh;
	GUI.markers = slidemarkh;
	GUI.textboxes = edittexth;
	GUI.warnings = safetytexth;
	GUI.HOME = homebuttonh;
end